---
driver:
  name: vagrant

platforms:
  - name: ubuntu-14.04

provisioner:
  name: salt_solo
  state_collection: true
  # This is a stub so kitchen doesn't bail when no pillars are defined
  pillars:
    top.sls:
      stubbing_for_file
  pillars-from-files:
    top.sls:
      '.travis/pillar/base/top.sls'
    users.sls:
      '.travis/pillar/base/users.sls'
  state_top:
    base:
      '*':
        - base.common.users
        - base.common.packages
        - base.common.gems

suites:
  - name: common
  - name: webhead
    state_top:
      base:
        '*':
          - base.webhead.nginx
          - base.webhead.site_content
