language: ruby
rvm:
- 2.1.5
addons:
  hosts:
  - salt
before_install:
- sudo add-apt-repository ppa:saltstack/salt -y
- sudo apt-get update
- sudo apt-get install salt-minion
- sudo cp .travis/minion /etc/salt/minion
- sudo mkdir -p /srv/salt
- sudo cp -rv srv/salt/* /srv/salt/
- sudo mkdir /srv/pillar
- sudo cp -rv .travis/pillar/* /srv/pillar/
- sudo service salt-minion restart
- sudo cat /var/log/salt/*
script:
- sudo salt-call state.show_highstate --local --retcode-passthrough
- sudo salt-call state.highstate --local --retcode-passthrough
- sudo source /home/travis/.bashrc
- sudo 'export HOME=/home/travis && source /home/travis/.bashrc && bundle exec rake spec'
notifications:
  slack:
    secure: qTuH2CygEtqoG+6l08F6eKFViSYTbzn6ct7VWvTceSUjMoeoA6q4WzE2jh3EGpQhTcAenl4JoBFz3l4iO48z5ATQ340dMVqr5O46I5xK7YA00EHuOSP8JVpwubkTxBnDoD3/MB7+KDX4mFFpgTrlRh0ZFdMeF6y/+jDybcbdkcA=
