# Saltstack is Python-based, but Python is significantly easier to manage than Ruby dependencies for Serverspec
# Defer to Travis for management of Ruby dependencies as much as possible
language: ruby
rvm:
  - 2.1.5

addons:
  hosts:
    - salt

before_install:
  - sudo add-apt-repository ppa:saltstack/salt -y
  - sudo apt-get update
  - sudo apt-get install salt-minion

install:
  # Copy minion config
  - sudo cp .travis/minion /etc/salt/minion

  # Copy states
  - sudo mkdir -p /srv/salt
  - sudo cp -rv srv/salt/* /srv/salt/

  # Copy pillars
  - sudo mkdir /srv/pillar
  - sudo cp -rv .travis/pillar/* /srv/pillar/

  # Apply
  - sudo service salt-minion restart

  # Additional debug help in case the restart fails
  - sudo cat /var/log/salt/*

  # See what kind of travis box you're on
  # to help with making your states compatible with travis
  - sudo salt-call grains.items --local

script:
  # Basic validation
  - sudo salt-call state.show_highstate --local --retcode-passthrough

  # Run states
  - sudo salt-call state.highstate --local --retcode-passthrough

  # Remove this
  - ruby --version

  # Integration tests will go here eventually
