language: python
python:
  - '2.7'

addons:
  hosts:
    - salt

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- git develop

install:
  # Copy these states
  - sudo mkdir -p /srv/salt/states
  - sudo cp -r . /srv/salt/states
  - sudo cp .travis/minion /etc/salt/minion

  # Copy pillars
  - sudo mkdir /srv/pillar
  - sudo cp -r .travis/pillar/* /srv/pillar/

  # Apply
  - sudo service salt-minion restart

  # Additional debug help
  - sudo cat /var/log/salt/minion

  # See what kind of travis box you're on
  # to help with making your states compatible with travis
  #- sudo salt-call grains.items --local

script:
  - sudo salt-call state.show_highstate --local --retcode-passthrough
